### ISSUE TITLE
Libsecret encryption is not working on ubuntu

### ISSUE THREAD

**Issue by billuk21** [AzureAD/microsoft-authentication-extensions-for-python#106]
I installed the new AZ CLI tool version 2.32.0.
Linux version: Linux ubuntu 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Python version: 3.8.0
And I saw from the documentation that the LibSecret is now supported in Linux. 
I used the AZ login to connect (username and password) to azure and it created the msal_tken_cache.json file within the .azure folder in the user's home folder, which has sensitive content in it (same as Accesstokens.json file had) and is not encrypted in any way (clear-text).

I then went into the python file in the repository and installed everything it asked for:
https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/60c2a745e3bd8ae61e51b60cae541cae74053b99/msal_extensions/libsecret.py
pip install pygobject
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (3.36.0)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from pygobject) (1.16.2)

And saw a comment about installing the pygobject library and then retried again to log in and the same files were there and still not encrypted.

I then thought maybe, it will not be accessible from any other users in the OS, but I created a different user and I was able to access the files as before. 

How does the encryption is being reflected here? Am is doing something wrong? 

Thanks,
Bill

**Comment by billuk21** [comment]
?

**Comment by rayluo** [comment]
Hi Bill (@billuk21) , thanks for your patience. There are 2 separated issues you mentioned.

> I saw from the documentation that the LibSecret is now supported in Linux.
I used the AZ login to connect (username and password) to azure and it created the msal_tken_cache.json file within the .azure folder in the user's home folder, which has sensitive content in it (same as Accesstokens.json file had) and is not encrypted in any way (clear-text).

1. Azure CLI has not yet enable token encryption when running on Linux, partially because we are still ironing out how to pack its dependencies into Azure CLI installation package. You should probably create a dedicated issue in Azure CLI's github repo for this feature request.
   (Here I'm looping in Azure CLI's engineer @jiasli: Jiashuo, since a determined customer can opt for installing the dependencies by themselves, it would be great if we can somehow provide a flag in configuration to allow customer to opt in for token encryption on Linux.)

> I then thought maybe, it will not be accessible from any other users in the OS, but I created a different user and I was able to access the files as before.

2. We are working on a PR #107 for this. Once it is shipped, we will close this issue.
