### ISSUE TITLE
DP API Tests Fail in TravisCI

### ISSUE THREAD

**Issue by marstr** [AzureAD/microsoft-authentication-extensions-for-python#21]
Some thing about the Windows Build Machines in TravisCI will not allow DP API calls. Each time, an OSError with errno=5 is returned.

These scenarios work on individual's machines, which means the core scenarios of this library are met. However, we need to figure out what it is about the TravisCI build machines is preventing this from working and either fix-it or understand the problem well enough to permanently skip these tests in CI. Until that investigation is done, a TODO is going in the code-base  to fix this issue.

**Comment by henrik-me** [comment]
@marstr : is this issue still relevant?

**Comment by rayluo** [comment]
I remember Martin used this issue as a memo. This was more about our known observation on Travis-CI's behavior, and less about an actual bug on our side.
I think we can keep it as-is, revisit this when we would start a second wave of effort on this Extensions module in future.

**Comment by rayluo** [comment]
Decided to close this.

We simply [recorded such observation in our test case](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.2.2/tests/test_persistence.py#L32-L34). FWIW, [encryption won't work on headless Linux](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.2.2/tests/test_persistence.py#L45-L47) either. There is not much else we can do about it.

We are still confident of our code's quality here, because those encryption-relevant code path were manually tested while we implemented/modified them. Since then they remain stable.
