### ISSUE TITLE
Create Token Cache Provider

### ISSUE THREAD

**Issue by marstr** [AzureAD/microsoft-authentication-extensions-for-python#6]
If an MSAL Token cache has been serialized into a well-known location, and the current user has access to it, this Token Provider should be able to reach-into that cache and get a token with the appropriate scopes for a user.

**Comment by rayluo** [comment]
Closing old issues. This one seemed to be a behavior which MSAL EX supported since early days, anyway. In fact, [app developers can and must specify a location](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.3.0/sample/token_cache_sample.py#L33). If such a location is "well-known" by several apps, those apps would be able to reach into that location/cache and get the content from it.
