### ISSUE TITLE
Roadmap for first stable release

### ISSUE THREAD

**Issue by chlowell** [AzureAD/microsoft-authentication-extensions-for-python#79]
`setup.cfg` [marks this package as pre-alpha](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/bd930e822acee13c14a686410821d32b4e2fe138/setup.cfg#L11). Is there a roadmap or timeline for an officially stable release?

**Comment by rayluo** [comment]
Oh, that "pre-alpha" thing was copied from [`setup.py`, which was written that way during the early days](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blame/0.3.0/setup.py#L23). I would say we have long been in "beta with production-level support". :-)

There are 2 foreseeable breaking changes down the road:

* It is likely we would remove the `serialize()` and `deserialize()` (i.e. #77)
* We will likely also change the API, in order to address the [performance concern](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/256)

But if you do not directly depend on [`PersistedTokenCache`](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.3.0/msal_extensions/__init__.py#L13), the changes above would be transparent to you.

Looping in our PM @navyasric .

**Comment by rayluo** [comment]
[Created a kanban](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/projects/4?add_cards_query=is%3Aopen) for this. Let's keep track at there.
