### ISSUE TITLE
Please remove cryptography upper version dependency

### ISSUE THREAD

**Issue by mihaimyh** [AzureAD/microsoft-authentication-extensions-for-python#98]
msal-extensions has a requirement of cryptography <4, but currently cryptography changed the versioning strategy, latest version being 35.0.0.

Due to this my project always tries to install cryptography 3.4.8 and fails.

```
- msal-extensions [required: ~=0.3.0, installed: 0.3.0]
    - msal [required: >=0.4.1,<2.0.0, installed: 1.12.0]
      - cryptography [required: >=0.6,<4, installed: 3.4.7]
        - cffi [required: >=1.12, installed: 1.14.5]
          - pycparser [required: Any, installed: 2.20]
      - PyJWT [required: >=1.0.0,<3, installed: 2.1.0]
      - requests [required: >=2.0.0,<3, installed: 2.25.1]
        - certifi [required: >=2017.4.17, installed: 2021.5.30]
        - chardet [required: >=3.0.2,<5, installed: 4.0.0]
        - idna [required: >=2.5,<3, installed: 2.10]
        - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
```

**Comment by rayluo** [comment]
> msal-extensions has a requirement of cryptography <4

[`msal-extensions` only has a direct dependency of `msal`, but not `cryptography`](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.3.0/setup.py#L27).

The cryptography 35.0.0 topic only needs to be addressed in msal. Closing this issue here in `msal-extensions` repo.
